changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        - deprecation
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documentation 📚
      labels:
        - docs
    - title: Other Changes 🔄
      labels:
        - "*"
