minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  - zudoku
  - react-router@7.12.0

packages:
  - "scripts"
  - "packages/*"
  - "examples/**"
  - "website"
  - "docs"

catalog:
  react: 19.2.3
  react-dom: 19.2.3
  react-is: 19.2.3
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/react-is": 19.2.0
  "@types/node": 22.19.1
