packages:
  - "scripts"
  - "packages/*"
  - "examples/**"
  - "website"
  - "docs"

catalog:
  react: 19.0.0
  react-dom: 19.0.0
  react-is: 19.0.0
  "@types/react": 19.0.7
  "@types/react-dom": 19.0.3
  "@types/react-is": 19.0.0
