packages:
  - scripts
  - packages/*
  - examples/**
  - website
  - docs

catalog:
  "@testing-library/dom": 10.4.1
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  "@testing-library/user-event": 14.6.1
  "@types/node": 22.19.1
  "@types/react": 19.2.10
  "@types/react-dom": 19.2.3
  "@types/react-is": 19.2.0
  happy-dom: 20.6.1
  react: 19.2.4
  react-dom: 19.2.4
  react-is: 19.2.4

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - zudoku
  - react-router@7.12.0
  - pagefind
  - tar@7.5.7
  - react@19.2.4
  - react-dom@19.2.4
  - react-is@19.2.4
  - "@types/react@19.2.10"
  - "@types/react-dom@19.2.4"
  - "@pagefind/*"
