packages:
  - scripts
  - packages/*
  - examples/**
  - website
  - docs

catalog:
  "@testing-library/dom": 10.4.1
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  "@testing-library/user-event": 14.6.1
  "@types/node": 22.19.1
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@types/react-is": 19.2.0
  happy-dom: 20.6.1
  react: 19.2.4
  react-dom: 19.2.4
  react-is: 19.2.4
  tsdown: 0.20.3

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - zudoku
  - glob
  - pagefind
  - "@pagefind/*"
  - oxfmt
  - "@oxfmt/*"
  - tailwind-merge
  - tailwindcss
  - "@tailwindcss/*"
  - lucide-react

onlyBuiltDependencies:
  - esbuild

overrides:
  "@supabase/auth-ui-react>react": "catalog:"
  "@supabase/auth-ui-react>react-dom": "catalog:"
  bs58: ">=6"
  js-yaml: ">=4.1.1"
  minimatch: ">=10.2.1"
  qs: ">=6.14.1"

patchedDependencies:
  decode-named-character-reference@1.2.0: patches/decode-named-character-reference@1.2.0.patch
