import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format } from "oxfmt";

const icons = await import("lucide-react/dynamicIconImports.mjs").then(
  (module) => module.default,
);

const iconNames = Object.keys(icons)
  .sort()
  .map((icon) => `"${icon}"`)
  .join(",");

const { code, errors } = await format(
  "icon-types.ts",
  `/* Generated by scripts/generate-types.js */
export const IconNames = [${iconNames}] as const;
export type IconNames = (typeof IconNames)[number];
export type LucideName = IconNames;
// Any iconify \`prefix:name\` string; lucide names (bare or \`lucide:\` prefixed) autocomplete.
export type IconName = LucideName | \`lucide:\${LucideName}\` | (string & {});
`,
);

if (errors.length > 0) {
  // biome-ignore lint/suspicious/noConsole: Logging allowed here
  console.error(errors);
  process.exit(1);
}

const outputPath = fileURLToPath(
  new URL("../src/config/validators/icon-types.ts", import.meta.url),
);
await writeFile(outputPath, code);
