import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format } from "oxfmt";

const icons = await import("lucide-react/dist/esm/dynamicIconImports.js").then(
  (module) => module.default,
);

const iconNames = Object.keys(icons)
  .sort()
  .map((icon) => `"${icon}"`)
  .join(",");

const { code, errors } = await format(
  "icon-types.ts",
  `/* Generated by scripts/generate-types.js */
export const IconNames = [${iconNames}] as const;
export type IconNames = (typeof IconNames)[number];
`,
);

if (errors.length > 0) {
  // biome-ignore lint/suspicious/noConsole: Logging allowed here
  console.error(errors);
  process.exit(1);
}

const outputPath = fileURLToPath(
  new URL("../src/config/validators/icon-types.ts", import.meta.url),
);
await writeFile(outputPath, code);

// Generate shiki code
const { languageNames } = await import("@shikijs/langs");
const { themeNames } = await import("@shikijs/themes");

const generateFiles = async (items: readonly string[], type: string) => {
  const dir = fileURLToPath(new URL(`../src/shiki/${type}`, import.meta.url));
  await mkdir(dir, { recursive: true });

  for (const item of items) {
    await writeFile(
      fileURLToPath(
        new URL(`../src/shiki/${type}/${item}.js`, import.meta.url),
      ),
      `export { default } from "@shikijs/${type}/${item}";\n`,
    );
  }
};

await Promise.all([
  generateFiles(languageNames, "langs"),
  generateFiles(themeNames, "themes"),
]);
