import type { TranslationCatalog } from "../../core/i18n.js";

/**
 * Default (English) translations for the OpenAPI plugin. Add new keys here and
 * reference them via `useTranslation()` in components.
 */
export const openapiTranslations: TranslationCatalog = {
  en: {
    // Schema download (DownloadSchemaButton)
    "openapi.downloadSchema": "Download schema",
    "openapi.openInNewTab": "Open in new tab",
    "openapi.copyToClipboard": "Copy to clipboard",

    // Sidecar / examples
    "openapi.exampleRequestBody": "Example Request Body",
    "openapi.exampleResponses": "Example Responses",
    "openapi.exampleAutoGenerated":
      "This example is auto-generated from the schema.",
    "openapi.toggleRequestBodyExamples": "Toggle request body examples",
    "openapi.toggleResponseExamples": "Toggle response examples",
    "openapi.viewExternalExample": "View External Example",
    "openapi.noExampleSpecified": "No example specified for this content type",

    // Parameters
    "openapi.parameter.required": "required",
    "openapi.parameter.toggle": "Toggle parameter",
    "openapi.headers": "Headers",
    "openapi.parametersOfGroup": "{group} Parameters",

    // Endpoint / server selector
    "openapi.server": "Server",
    "openapi.selectServer": "Select server",
    "openapi.copyServerUrl": "Copy server URL",

    // Operation list item
    "openapi.requestBody": "Request Body",
    "openapi.optional": "optional",
    "openapi.responses": "Responses",

    // Api header
    "openapi.selectVersion": "Select version",

    // Security requirements
    "openapi.requiredScopes": "Required scopes:",
    "openapi.scopesSeparatorOr": "or",
    "openapi.scopesSeparatorAnd": "+",

    // Collapsible code
    "openapi.clickToExpand": "Click to expand",
    "openapi.collapse": "Collapse",

    // Schema info / info card
    "openapi.termsOfService": "Terms of Service",
    "openapi.documentation": "Documentation",
    "openapi.contact": "Contact",
    "openapi.servers": "Servers",
    "openapi.tags": "Tags",
    "openapi.securitySchemes": "Security Schemes",
    "openapi.webhooks": "Webhooks",

    // Operation list / empty states
    "openapi.noOperations": "No operations found",
    "openapi.noOperationsDescription":
      "This API doesn't have any operations defined yet.",
    "openapi.otherEndpoints": "Other endpoints",

    // Schemas list
    "openapi.schemas": "Schemas",
    "openapi.schemasMetaDescription": "List of schemas used by the API.",
    "openapi.noSchemas": "No schemas found",
  },
};
