/**
 * Japanese (日本語) translation for Cosmo Cargo
 */
export const ja = {
  // Common
  "common.copy": "コピー",
  "common.copyCode": "コードをコピー",
  "common.copyToClipboard": "クリップボードにコピー",
  "common.cancel": "キャンセル",
  "common.delete": "削除",
  "common.error": "エラー",
  "common.send": "送信",
  "common.name": "名前",
  "common.value": "値",

  // Code blocks
  "code.copy": "コピー",
  "code.copyCode": "コードをコピー",
  "code.defaultTitle": "コード",
  "code.clickToExpand": "クリックして展開",
  "code.collapse": "折りたたむ",

  // OpenAPI Playground
  "openapi.playground.send": "送信",
  "openapi.playground.cancel": "キャンセル",
  "openapi.playground.authentication": "認証",
  "openapi.playground.pathParameters": "パスパラメータ",
  "openapi.playground.queryParameters": "クエリパラメータ",
  "openapi.playground.headers": "ヘッダー",
  "openapi.playground.body": "ボディ",
  "openapi.playground.sendHint": "でリクエストを送信",
  "openapi.playground.requestFailedNetwork":
    "ネットワークの問題またはCORSポリシーにより、リクエストが失敗した可能性があります。",

  "openapi.playground.field.name": "名前",
  "openapi.playground.field.value": "値",
  "openapi.playground.field.key": "キー",
  "openapi.playground.field.requiredField": "必須フィールド",
  "openapi.playground.field.queryParamValue": "クエリパラメータの値",
  "openapi.playground.header.lockedByAuth":
    "このヘッダーは選択された認証によって設定されています。",
  "openapi.playground.header.overwrittenByAuth":
    "このヘッダーは選択された認証によって上書きされます。",

  "openapi.playground.body.text": "テキスト",
  "openapi.playground.body.file": "ファイル",
  "openapi.playground.body.multipart": "マルチパート",
  "openapi.playground.body.placeholder": "ボディの内容",
  "openapi.playground.body.fileDropZone": "ファイルドロップゾーン",
  "openapi.playground.body.selectOrDropFile": "ファイルを選択またはドロップ",
  "openapi.playground.body.attachFile": "ファイルを添付",

  "openapi.playground.result.requestFailed": "リクエスト失敗",
  "openapi.playground.result.sendFirstRequest":
    "最初のリクエストを送信してください",
  "openapi.playground.result.longRunning":
    "リクエストの処理に予想以上の時間がかかっています。",
  "openapi.playground.result.sendingRequest": "リクエスト送信中...",

  "openapi.playground.response.requestHeaders": "リクエストヘッダー",
  "openapi.playground.response.responseHeaders": "レスポンスヘッダー",
  "openapi.playground.response.responseBody": "レスポンスボディ",
  "openapi.playground.response.view": "表示",
  "openapi.playground.response.formatted": "フォーマット済み",
  "openapi.playground.response.raw": "生データ",
  "openapi.playground.response.types": "型",
  "openapi.playground.response.binaryContent": "バイナリコンテンツ",
  "openapi.playground.response.binaryDescription":
    "このレスポンスにはテキストとして表示できないバイナリデータが含まれています。",
  "openapi.playground.response.download":
    "{fileName} ({fileSize}) をダウンロード",
  "openapi.playground.response.showMoreHeaders":
    "さらに {count} 件のヘッダーを表示",
  "openapi.playground.response.hideHeaders": "{count} 件のヘッダーを非表示",
  "openapi.playground.response.size": "サイズ",
  "openapi.playground.response.time": "時間",

  "openapi.playground.login.title": "Playgroundへようこそ！",
  "openapi.playground.login.description":
    "PlaygroundはAPIをテスト・探索するための開発者ツールです。使用するにはログインが必要です。",
  "openapi.playground.login.dontShowAgain": "今後表示しない",
  "openapi.playground.login.skip": "スキップ",
  "openapi.playground.login.signUp": "新規登録",
  "openapi.playground.login.login": "ログイン",

  "openapi.playground.identity.selectTitle": "認証IDを選択",
  "openapi.playground.identity.selectDescription":
    "このリクエストのIDを選択してください。",
  "openapi.playground.identity.rememberChoice": "選択を記憶する",
  "openapi.playground.identity.none": "なし",

  "openapi.playground.examples.useExample": "例を使用",

  // Schema
  "openapi.schema.required": "必須",
  "openapi.schema.deprecated": "非推奨",
  "openapi.schema.circular": "循環参照",
  "openapi.schema.noDataReturned": "データなし",
  "openapi.schema.additionalProperties": "追加プロパティが許可されています",
  "openapi.schema.hideDeprecatedFields": "非推奨フィールドを非表示",
  "openapi.schema.showDeprecatedFields": "{count} 件の非推奨フィールドを表示",
  "openapi.schema.toggleProperties": "プロパティを切り替え",
  "openapi.schema.example": "例: ",
  "openapi.schema.default": "デフォルト: ",
  "openapi.schema.enumValues": "列挙値:",
  "openapi.schema.showMore": "さらに {count} 件を表示",
  "openapi.schema.showLess": "折りたたむ",

  // Parameters
  "openapi.parameters.headers": "ヘッダー",
  "openapi.parameters.groupParameters": "{group}パラメータ",
  "openapi.parameters.toggleParameter": "パラメータを切り替え",

  // Download
  "openapi.download.schema": "スキーマをダウンロード",
  "openapi.download.openInNewTab": "新しいタブで開く",

  // Version
  "openapi.version.select": "バージョンを選択",

  // Sidecars
  "openapi.sidecar.exampleRequestBody": "リクエストボディの例",
  "openapi.sidecar.exampleResponses": "レスポンスの例",
  "openapi.sidecar.toggleRequestBodyExamples": "リクエストボディの例を切り替え",
  "openapi.sidecar.toggleResponseExamples": "レスポンスの例を切り替え",
  "openapi.sidecar.autoGenerated": "この例はスキーマから自動生成されています。",

  // Search
  "search.placeholder": "検索...",
  "search.noResults": "結果が見つかりませんでした。",
  "search.clearSearch": "検索をクリア",
  "search.startTyping": "入力して検索を開始",
  "search.errorLoading": "検索の読み込み中にエラーが発生しました。",
  "search.navigate": "移動",
  "search.select": "選択",
  "search.closeDialog": "ダイアログを閉じる",
  "search.buildIndex": "検索インデックスを構築",

  // API Keys
  "apiKeys.title": "APIキー",
  "apiKeys.description": "APIキーの作成、管理、監視",
  "apiKeys.createKey": "APIキーを作成",
  "apiKeys.generateKey": "キーを生成",
  "apiKeys.name": "名前",
  "apiKeys.expiration": "有効期限",
  "apiKeys.days": "{count}日",
  "apiKeys.never": "無期限",
  "apiKeys.defaultName": "シークレットキー",
  "apiKeys.emptyState": "APIキーがまだありません。",
  "apiKeys.emptyStateHint": "最初のキーを作成して始めましょう。",
  "apiKeys.rollDialog.title": "APIキーをローテーション",
  "apiKeys.rollDialog.description":
    "このAPIキーをローテーションしてもよろしいですか？",
  "apiKeys.rollDialog.confirm": "ローテーション",
  "apiKeys.deleteDialog.title": "APIキーを削除",
  "apiKeys.deleteDialog.description": "このAPIキーを削除してもよろしいですか？",
  "apiKeys.created": "{timeAgo}に作成されました。",
  "apiKeys.expiresIn": "{count}{dayLabel}後に期限切れ。",
  "apiKeys.expiredToday": "本日期限切れ。",
  "apiKeys.expiredDaysAgo": "{count}日前に期限切れ。",

  // Status pages
  "status.400.title": "不正なリクエスト",
  "status.400.message":
    "構文が正しくないため、サーバーがリクエストを理解できませんでした。",
  "status.403.title": "アクセス拒否",
  "status.403.message": "このリソースにアクセスする権限がありません。",
  "status.404.title": "見つかりません",
  "status.404.message": "リクエストされたリソースが見つかりませんでした。",
  "status.500.title": "内部サーバーエラー",
  "status.500.message": "リクエストの処理中に予期しないエラーが発生しました。",
  "status.default.title": "エラーが発生しました",
  "status.default.message": "リクエストの処理中に問題が発生しました。",

  // Not Found
  "notFound.title": "ページが見つかりません",
  "notFound.description":
    "お探しのページは存在しないか、移動された可能性があります。URLを確認するか、ナビゲーションメニューから正しいページをお探しください。",
  "notFound.goHome": "ホームに戻る",

  // Docs
  "docs.editThisPage": "このページを編集",
  "docs.copyPage": "ページをコピー",
  "docs.copyLinkToPage": "ページリンクをコピー",
  "docs.openMarkdownPage": "Markdownページを開く",
  "docs.pageActions": "ページアクション",
  "docs.lastModifiedOn": "最終更新日: ",
  "docs.draft": "このページは下書きであり、本番環境では表示されません。",

  // MCP
  "mcp.endpointTitle": "MCPエンドポイント",
  "mcp.endpointDescription": "MCP対応のAIツールに接続するためのURLをコピー",
  "mcp.configurationTitle": "AIツール設定",
  "mcp.configurationDescription":
    "AIツールを選択して設定をコピーしてください。",
  "mcp.viewOfficialDocs": "公式ドキュメントを見る",
} as const;
