import { describe, expect, it } from "vitest";
import { generateConfig } from "./generate.js";
import { CONFIG_SPEC_SCHEMA_URL } from "./spec.js";

const exampleSpec = {
  $schema: CONFIG_SPEC_SCHEMA_URL,
  metadata: { title: "Acme" },
  apis: [
    {
      type: "url",
      input: "https://api.acme.dev/openapi.json",
      path: "api",
    },
  ],
  plugins: [
    {
      id: "graphql",
      options: {
        type: "url",
        input: "https://api.acme.dev/graphql",
        path: "graphql",
      },
    },
    {
      id: "monetization",
      options: { pricing: { title: "Plans" } },
    },
  ],
};

describe("generateConfig", () => {
  it("generates a typed config module from a spec", () => {
    expect(generateConfig(exampleSpec)).toMatchInlineSnapshot(`
      "// Generated by \`zudoku generate\`. Do not edit.
      import { graphqlPlugin } from "@zudoku/plugin-graphql";
      import { zuploMonetizationPlugin } from "@zuplo/zudoku-plugin-monetization";
      import type { ZudokuConfig } from "zudoku";

      const config: ZudokuConfig = {
        metadata: {
          title: "Acme",
        },
        apis: [
          {
            type: "url",
            input: "https://api.acme.dev/openapi.json",
            path: "api",
          },
        ],
        plugins: [
          graphqlPlugin({
            type: "url",
            input: "https://api.acme.dev/graphql",
            path: "graphql",
          }),
          zuploMonetizationPlugin({
            pricing: {
              title: "Plans",
            },
          }),
        ],
      };

      export default config;
      "
    `);
  });

  it("calls factories without arguments when options are omitted", () => {
    const generated = generateConfig({ plugins: [{ id: "monetization" }] });

    expect(generated).toContain("zuploMonetizationPlugin(),");
  });

  it("imports a plugin once even when referenced multiple times", () => {
    const options = { type: "file", input: "./a.graphql", path: "a" };
    const generated = generateConfig({
      plugins: [
        { id: "graphql", options },
        { id: "graphql", options: { ...options, path: "b" } },
      ],
    });

    expect(generated.match(/import \{ graphqlPlugin \}/g)).toHaveLength(1);
    expect(generated.match(/graphqlPlugin\(/g)).toHaveLength(2);
  });

  it("quotes keys that are not valid identifiers", () => {
    const generated = generateConfig({
      theme: { customCss: { ".my-class": { color: "red" } } },
    });

    expect(generated).toContain(`".my-class": {`);
  });

  it("works without a $schema (assumes the current version)", () => {
    expect(generateConfig({ metadata: { title: "No Schema" } })).toContain(
      `title: "No Schema"`,
    );
  });

  it("rejects a non-object spec", () => {
    expect(() => generateConfig([])).toThrow(/must be a JSON object/);
    expect(() => generateConfig("nope")).toThrow(/must be a JSON object/);
  });

  it("rejects an unknown $schema", () => {
    expect(() =>
      generateConfig({ $schema: "https://example.com/other.json" }),
    ).toThrow(/Unknown config spec \$schema/);
  });

  it("rejects an unsupported spec version", () => {
    expect(() =>
      generateConfig({
        $schema: "https://schemas.zudoku.dev/config-spec/v999.json",
      }),
    ).toThrow(/Unsupported config spec version v999/);
  });

  it("rejects unknown top-level keys", () => {
    expect(() => generateConfig({ metdata: { title: "typo" } })).toThrow(
      /Invalid config spec/,
    );
  });

  it("rejects unknown plugin ids with the available ids", () => {
    expect(() => generateConfig({ plugins: [{ id: "nope" }] })).toThrow(
      /Unknown plugin id "nope". Available plugins: graphql, monetization./,
    );
  });

  it("rejects invalid plugin options with the plugin id in the message", () => {
    expect(() =>
      generateConfig({
        plugins: [{ id: "graphql", options: { type: "url" } }],
      }),
    ).toThrow(/Invalid options for plugin "graphql"/);
  });

  it("rejects non-serializable config keys", () => {
    expect(() => generateConfig({ slots: {} })).toThrow(/Invalid config spec/);
    expect(() => generateConfig({ extends: [] })).toThrow(
      /Invalid config spec/,
    );
  });
});
