import { getPresetPlugin } from "../config/preset-registry.js";
import { type ConfigSpec, validateSpec } from "./spec.js";

const INDENT = "  ";

const isIdentifier = (key: string) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);

const serializeKey = (key: string) =>
  isIdentifier(key) ? key : JSON.stringify(key);

// Emits a TS expression for a JSON value. JSON is a subset of TS expressions,
// so this is plain pretty-printing with unquoted identifier keys.
const serializeValue = (value: unknown, depth: number): string => {
  if (value === null) return "null";

  switch (typeof value) {
    case "string":
      return JSON.stringify(value);
    case "number":
    case "boolean":
      return JSON.stringify(value);
  }

  const outer = INDENT.repeat(depth);
  const inner = INDENT.repeat(depth + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map(
      (item) => `${inner}${serializeValue(item, depth + 1)},`,
    );
    return `[\n${items.join("\n")}\n${outer}]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value).filter(
      ([, entry]) => entry !== undefined,
    );
    if (entries.length === 0) return "{}";
    const lines = entries.map(
      ([key, entry]) =>
        `${inner}${serializeKey(key)}: ${serializeValue(entry, depth + 1)},`,
    );
    return `{\n${lines.join("\n")}\n${outer}}`;
  }

  throw new Error(`Cannot serialize value of type "${typeof value}" in spec.`);
};

const buildPluginExpression = (
  ref: NonNullable<ConfigSpec["plugins"]>[number],
  depth: number,
): string => {
  // validateSpec guarantees the descriptor exists.
  // biome-ignore lint/style/noNonNullAssertion: validated above
  const descriptor = getPresetPlugin(ref.id)!;
  const args =
    ref.options === undefined ? "" : serializeValue(ref.options, depth);

  return `${descriptor.export}(${args})`;
};

/**
 * Turns a serializable config spec into the source of a typed Zudoku config
 * module: static imports for each referenced preset plugin, factory calls
 * with the validated options, and the remaining spec keys as literals.
 *
 * The result is meant to be written next to the user's config and composed
 * via `extends`:
 *
 * ```ts
 * import base from "./zudoku.base.js";
 * export default { extends: [base], ... };
 * ```
 */
export const generateConfig = (spec: unknown): string => {
  const validated = validateSpec(spec);
  const { $schema: _schema, plugins = [], ...core } = validated;

  const imports = [
    ...new Map(
      plugins.map((ref) => {
        // biome-ignore lint/style/noNonNullAssertion: validated in validateSpec
        const descriptor = getPresetPlugin(ref.id)!;
        return [
          descriptor.specifier,
          `import { ${descriptor.export} } from "${descriptor.specifier}";`,
        ];
      }),
    ).values(),
  ].sort();

  const configLines = Object.entries(core)
    .filter(([, value]) => value !== undefined)
    .map(
      ([key, value]) =>
        `${INDENT}${serializeKey(key)}: ${serializeValue(value, 1)},`,
    );

  if (plugins.length > 0) {
    const pluginLines = plugins.map(
      (ref) => `${INDENT.repeat(2)}${buildPluginExpression(ref, 2)},`,
    );
    configLines.push(
      `${INDENT}plugins: [\n${pluginLines.join("\n")}\n${INDENT}],`,
    );
  }

  return [
    "// Generated by `zudoku generate`. Do not edit.",
    ...imports,
    `import type { ZudokuConfig } from "zudoku";`,
    "",
    `const config: ZudokuConfig = {\n${configLines.join("\n")}\n};`,
    "",
    "export default config;",
    "",
  ].join("\n");
};
