import { describe, expect, it } from "vitest";
import { generateConfigSource } from "./codegen.js";

describe("generateConfigSource", () => {
  it("emits an empty typed config for an empty spec", () => {
    expect(generateConfigSource({})).toMatchInlineSnapshot(`
      "// Generated by \`zudoku generate\` — do not edit.
      import type { ZudokuConfig } from "zudoku";

      const config = {
      } satisfies ZudokuConfig;

      export default config;
      "
    `);
  });

  it("emits fields verbatim and plugins as static imports", () => {
    const source = generateConfigSource(
      {
        $schema: "https://zudoku.dev/spec.schema.json",
        site: { title: "My Portal" },
        apis: [
          { type: "file", input: "../config/routes.oas.json", path: "/api" },
        ],
        plugins: [
          {
            name: "graphql",
            options: {
              type: "url",
              input: "https://gateway.example.com/graphql",
              path: "/graphql",
            },
          },
        ],
      },
      { specFile: "spec.json" },
    );

    expect(source).toMatchInlineSnapshot(`
      "// Generated by \`zudoku generate\` from spec.json — do not edit.
      import { graphqlPlugin } from "@zudoku/plugin-graphql";
      import type { ZudokuConfig } from "zudoku";

      const config = {
        "site": {
          "title": "My Portal"
        },
        "apis": [
          {
            "type": "file",
            "input": "../config/routes.oas.json",
            "path": "/api"
          }
        ],
        plugins: [
          graphqlPlugin({
            "type": "url",
            "input": "https://gateway.example.com/graphql",
            "path": "/graphql"
          }),
        ],
      } satisfies ZudokuConfig;

      export default config;
      "
    `);
  });

  it("drops the $schema field and undefined values", () => {
    const source = generateConfigSource({
      $schema: "x",
      basePath: undefined,
      enableStatusPages: true,
    });

    expect(source).not.toContain("$schema");
    expect(source).not.toContain("basePath");
    expect(source).toContain(`"enableStatusPages": true,`);
  });
});
