import type { ZudokuSpec, ZudokuSpecPlugin } from "./schema.js";

// Maps spec plugin names to the static import the generated config uses.
// Plugins are code, so the spec only carries names + options and the
// generated layer holds the real imports.
const SPEC_PLUGIN_IMPORTS: Record<
  ZudokuSpecPlugin["name"],
  { module: string; importName: string }
> = {
  graphql: { module: "@zudoku/plugin-graphql", importName: "graphqlPlugin" },
};

const INDENT = "  ";

// JSON is valid TS; re-indent continuation lines to the nesting depth
const serialize = (value: unknown, depth: number): string =>
  JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : INDENT.repeat(depth) + line))
    .join("\n");

export type GenerateConfigSourceOptions = {
  /** Path of the source spec file, included in the file header */
  specFile?: string;
};

/**
 * Compiles a validated spec into the source of a typed Zudoku base config
 * layer. Serializable fields are emitted verbatim; `plugins` entries become
 * static plugin imports so the generated layer builds and renders like a
 * hand-written config.
 */
export const generateConfigSource = (
  spec: ZudokuSpec,
  { specFile }: GenerateConfigSourceOptions = {},
): string => {
  const { $schema: _, plugins = [], ...fields } = spec;

  const pluginImports = [...new Set(plugins.map(({ name }) => name))]
    .sort()
    .map((name) => {
      const { module, importName } = SPEC_PLUGIN_IMPORTS[name];
      return `import { ${importName} } from "${module}";`;
    });

  const fieldLines = Object.entries(fields)
    .filter(([, value]) => value !== undefined)
    .map(
      ([key, value]) =>
        `${INDENT}${JSON.stringify(key)}: ${serialize(value, 1)},`,
    );

  const pluginLines =
    plugins.length > 0
      ? [
          `${INDENT}plugins: [`,
          ...plugins.map(
            ({ name, options }) =>
              `${INDENT.repeat(2)}${SPEC_PLUGIN_IMPORTS[name].importName}(${serialize(options, 2)}),`,
          ),
          `${INDENT}],`,
        ]
      : [];

  return [
    `// Generated by \`zudoku generate\`${specFile ? ` from ${specFile}` : ""} — do not edit.`,
    ...pluginImports,
    `import type { ZudokuConfig } from "zudoku";`,
    "",
    "const config = {",
    ...fieldLines,
    ...pluginLines,
    "} satisfies ZudokuConfig;",
    "",
    "export default config;",
    "",
  ].join("\n");
};
