// Generated by `zudoku generate`. Do not edit.
import { graphqlPlugin } from "@zudoku/plugin-graphql";
import type { ZudokuConfig } from "zudoku";

const config: ZudokuConfig = {
  metadata: {
    title: "Cosmo Cargo GraphQL",
    description: "Interstellar shipping, one mutation away.",
  },
  redirects: [
    {
      from: "/",
      to: "/home",
    },
  ],
  plugins: [
    graphqlPlugin({
      type: "file",
      input: "./schema.graphql",
      path: "graphql",
      options: {
        title: "Shipment GraphQL API",
        description: "Track and book interstellar shipments.",
      },
    }),
  ],
};

export default config;
