# This action sync docs to the zuplo docs
name: Zuplo Docs
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Zuplo Docs Update
        run: curl ${{ secrets.VERCEL_DOCS_WEBHOOK_URL }}
