name: Release
on:
  push:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    name: Release
    runs-on:
      group: ubuntu-large-runners
    permissions:
      actions: read
      contents: write
      id-token: write
      pull-requests: read

    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ZUDOKU_GH_APP_ID }}
          private-key: ${{ secrets.ZUDOKU_GH_APP_PRIVATE_KEY }}
          repositories: |
            zuplo/docs
            zuplo/core
            zuplo/www

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      # Trigger updates of internal projects using Zudoku
      - run: gh workflow run update-zudoku.yaml --repo zuplo/docs --ref main
        # Only for non-prerelease
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: gh workflow run zudoku-builder.yaml --repo zuplo/core --ref main
        # Only for non-prerelease
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: gh workflow run zudoku-changelog.yml --repo zuplo/www --ref main
        # Only for non-prerelease and not patch
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.releaseType != 'patch' && github.event.inputs.releaseType != 'prerelease'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
