name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  test-examples:
    name: Test Example Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build example - api-identity-plugin
        run: cd examples/api-identity-plugin && pnpm install && pnpm build

      - name: Build example - api-key-service
        run: cd examples/api-key-service && pnpm install && pnpm build

      - name: Build example - with-auth0
        run: cd examples/with-auth0 && pnpm install && pnpm build

      - name: Build example - cosmo-cargo
        run: cd examples/cosmo-cargo && pnpm install && pnpm build

      - name: Build example - with-config
        run: cd examples/with-config && pnpm install && pnpm build

      - name: Build example - with-openapi-yaml
        run: cd examples/with-openapi-yaml && pnpm install && pnpm build

      - name: Build example - with-vite-config
        run: cd examples/with-vite-config && pnpm install && pnpm build

      - name: Build example - many-apis
        run: cd examples/many-apis && pnpm install && pnpm build

      - name: Build example - darkmatter
        run: cd examples/darkmatter && pnpm install && pnpm build

      - name: Build example - ship-happens
        run: cd examples/ship-happens && pnpm install && pnpm build

      - name: Build example - with-zuplo
        run: cd examples/with-zuplo && pnpm install && pnpm build

      - name: Build example - with-openapi-json
        run: cd examples/with-openapi-json && pnpm install && pnpm build
